# Generated by Django 5.0.7 on 2024-08-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=255)),
                ('pubDate', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=1000)),
                ('isbn', models.CharField(max_length=15)),
                ('itemId', models.CharField(max_length=20)),
                ('cover', models.CharField(max_length=500)),
                ('categoryName', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
            ],
        ),
    ]
